### ISSUE TITLE
Valve expanders?

### ISSUE THREAD

**Issue by mightymos** [hwstar/9-Valve-Sprinkler-Controller#3]
This is more of a feature request...

Scripting the watering program 1  for eight valves with ten minutes each was fairly straightforward.

The only wrinkle was needing to add the "--device" flag to command line to specify IP address for OTA once controller was physically installed.

I guess adding MAC to device name is a controversial feature (?):
https://github.com/esphome/issues/issues/4130
https://community.home-assistant.io/t/how-to-properly-turn-add-mac-suffix-to-true-and-ota-updates/320082

Anyway, turns out in addition to master valve I have nine valves/zones.
Is there any expectation for having expansion boards available?

I would be able to try being an early adopter (with double E background) but understand if it is not even designed yet.

![PXL_20230710_011208372](https://github.com/hwstar/9-Valve-Sprinkler-Controller/assets/26175234/f3471ab8-4206-40fa-b829-3fd6752c0263)

**Comment by hwstar** [comment]
I use it during bring up and test to help differentiate and distinguish between controllers on my network. As they they state in the link. I need some way to make them all different from one another.  As an end user you shouldn't need the mac address option, and you can remove it from your config.

The --device flag is totally non-intuitive. I don't know why they just didn't use something like --ip-address. I don't use .local IP addresses here. DHCP makes more sense (at least to me). By the way you can use home assistant to tell you what the IP address is instead of logging into a router if that is easier for you.

Actually, the only thing holding me back on the expansion board is user demand (you're the first one who has asked). What needs to be done: Getting the connecting cable designed, design a front panel graphic overlay, build a depopulated version of the current board, and testing it thoroughly. (Yes, the board blank is designed to work in both roles).

If I get a few more requests, I'll consider bumping it up in my prioirity queue. I'm working on other ESPHome related hardware as well.

**Comment by mightymos** [comment]
I admit the expander would be cool for me to have.
I suppose one option is I'll buy a few more controllers and put in additional requests lol. :)

Thanks for the OTA tips, appreciated.

**Comment by hwstar** [comment]
Here's a picture of the prototype valve expander hooked up to the gold board in my tester. It's still very early in the game for this as this prototype hasn't undergone any serious testing. The expander's valve control triacs live at device address 0x39. 
![expander](https://github.com/hwstar/9-Valve-Sprinkler-Controller/assets/1753715/c257df35-b7e2-473a-8eb3-6819dbc8e169)

**Comment by mightymos** [comment]
That's cool, it did not dawn on me before you would need dummy loads for testing.
The expander doesn't look too bad to assemble compared with the full board.
I'm not sure I recognize the cable, maybe like PCI express 8 pin type.

So there's basically just an I2C daughter chip that controls the triacs?
Would a git branch be needed to introduce expander support or is it just editing yaml as is?

**Comment by hwstar** [comment]
I wrote an automatic test program in Python to test these during production.
The cable uses 4.2mm Molex Mini-fit connectors series 43025.
Yes, the triacs are controlled with another PCA9554 I2C chip on the expander.
All that's needed is an updated yaml file.
Attached is the example yaml file.
[esp32-sprinkler-expander.yaml.zip](https://github.com/hwstar/9-Valve-Sprinkler-Controller/files/12005056/esp32-sprinkler-expander.yaml.zip)

**Comment by mightymos** [comment]
Cool, yaml seems more convenient than I'd originally thought.

So I understand either way, but if you happen to have a spare board (populated or unpopulated I suppose) I'd be happy to purchase and assemble for my own needs. I guess the cable pinout is given so no problem there to make. I'd understand it's unofficial and unsupported for now. Can discuss here or email is on my profile, but cool work.

**Comment by hwstar** [comment]
Check your email on file with github for information concerning this request.
